//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.07 at 05:23:40 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ncpdp.org/schema/SCRIPT", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sanchit.modals;
