//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.07 at 05:23:40 PM IST 
//


package org.sanchit.modals;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RouteofAdministrationText" type="{http://www.ncpdp.org/schema/SCRIPT}an..50" minOccurs="0"/>
 *         &lt;element name="RouteofAdministrationCodeQualifier" type="{http://www.ncpdp.org/schema/SCRIPT}TerminologyType" minOccurs="0"/>
 *         &lt;element name="RouteofAdministrationCode" type="{http://www.ncpdp.org/schema/SCRIPT}an..15" minOccurs="0"/>
 *         &lt;element name="MultipleRouteofAdministrationModifier" type="{http://www.ncpdp.org/schema/SCRIPT}ANDOR" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "routeofAdministrationText",
    "routeofAdministrationCodeQualifier",
    "routeofAdministrationCode",
    "multipleRouteofAdministrationModifier"
})
@XmlRootElement(name = "RouteofAdministration")
public class RouteofAdministration {

    @XmlElement(name = "RouteofAdministrationText")
    protected String routeofAdministrationText;
    @XmlElement(name = "RouteofAdministrationCodeQualifier")
    protected String routeofAdministrationCodeQualifier;
    @XmlElement(name = "RouteofAdministrationCode")
    protected String routeofAdministrationCode;
    @XmlElement(name = "MultipleRouteofAdministrationModifier")
    protected String multipleRouteofAdministrationModifier;

    /**
     * Gets the value of the routeofAdministrationText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteofAdministrationText() {
        return routeofAdministrationText;
    }

    /**
     * Sets the value of the routeofAdministrationText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteofAdministrationText(String value) {
        this.routeofAdministrationText = value;
    }

    /**
     * Gets the value of the routeofAdministrationCodeQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteofAdministrationCodeQualifier() {
        return routeofAdministrationCodeQualifier;
    }

    /**
     * Sets the value of the routeofAdministrationCodeQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteofAdministrationCodeQualifier(String value) {
        this.routeofAdministrationCodeQualifier = value;
    }

    /**
     * Gets the value of the routeofAdministrationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRouteofAdministrationCode() {
        return routeofAdministrationCode;
    }

    /**
     * Sets the value of the routeofAdministrationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRouteofAdministrationCode(String value) {
        this.routeofAdministrationCode = value;
    }

    /**
     * Gets the value of the multipleRouteofAdministrationModifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleRouteofAdministrationModifier() {
        return multipleRouteofAdministrationModifier;
    }

    /**
     * Sets the value of the multipleRouteofAdministrationModifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleRouteofAdministrationModifier(String value) {
        this.multipleRouteofAdministrationModifier = value;
    }

}
